name: Pipeline CI/CD UserAuthenticationService

on: [push]

jobs:
  probar-codigo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Ejecutar Tests
      run: dotnet test 

  construir-y-subir:
    needs: probar-codigo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Construir y Subir Imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./UserAuthenticationService.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/userauthenticationservice:latest